baseURL = "https://michaelhealy.space/prelims/"
languageCode = "en-us"
title = "Michael's Prelims Site"
publishdir = "docs"
theme = "one"
copyright = "&copy; Copyright notice"

[blackfriday]
hrefTargetBlank = true

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["categories/rhetoric", "categories/composition","categories/minor","categories/speciality","categories/reading-list"]
