baseURL = "https://michaelhealy.space/prelims/"
languageCode = "en"
title = "Michael's Prelims Site"
publishdir = "docs"
theme = "kiss"
copyright = "&copy; Copyright notice"
buildfuture = "true"
Paginate = 10
enableRobotsTXT = false

[taxonomies]
  category = "categories"
  tag = "tags"

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Michael Healy" # Site author's full name
authorEmail = "mjh16m@my.fsu.edu"

[params.info]
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "Lastest Entries" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.social]
twitter = "mhealy_rhet"
github = "mjh16"
email = "mjh16m@my.fsu.edu"
instagram = "mjhealy"

[blackfriday]
hrefTargetBlank = true

[params.sections_left]
"/posts/rehtoric-list" = "Rhetoric"
"/posts/composition-list" = "Composition"
"/posts/speciality-list" = "Speciality"
"/posts/minor-list" = "Minor"

[params.sections_right]
"/prelims/categories" = "Categories"
"/prelims/tags" = "Tags"
